version: '2'
services:
    hostmaker-mysql:
        image: mysql:5.7.20
        volumes:
            - ./volumes/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=my_secret_password
            - MYSQL_DATABASE=hostmaker_development
        ports:
            - 3306:3306
        command: mysqld --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp